[client]
toolbarMode = "minimal"
showSidebarNavigation = false


[theme]
base="light"
primaryColor="#3366cc"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f5f5f5"
textColor="#000000"
font="sans serif"
